export { default as usePresentationQuery } from "./usePresentationQuery";
export { default as useCreatePresentationMutation } from "./useCreatePresentationMutation";
export { default as useDeletePresentationMutation } from "./useDeletePresentationMutation";
export { default as useCreateSlideMutation } from "./useCreateSlideMutation";
export { default as useUpdateSlideContentMutation } from "./useUpdateSlideContentMutation";
export { default as useUpdateSlideAudioMutation } from "./useUpdateSlideAudioMutation";
export { default as useUpdateSlideActionMutation } from "./useUpdateSlideActionMutation";
export { default as useDeleteSlideMutation } from "./useDeleteSlideMutation";
export { default as useReorderSlidesMutation } from "./useReorderSlidesMutation";
